name: Base Image Create

on:
  workflow_dispatch:

concurrency:
  group: create-base-img
  cancel-in-progress: true

jobs:

  manylinux:
    name: ManyLinux • ${{ matrix.build_arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_arch: [ "arm64", "amd64", "armv7" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ARM64 prepare
        if: matrix.build_arch == 'arm64'
        run: |
          echo BASE_DOCKER_FILE="docker/manylinux64.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm64" >> $GITHUB_ENV

      - name: AMD64 prepare
        if: matrix.build_arch == 'amd64'
        run: |
          echo BASE_DOCKER_FILE="docker/manylinux64.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/amd64" >> $GITHUB_ENV

      - name: ARMv7 prepare
        if: matrix.build_arch == 'armv7'
        run: |
          echo BASE_DOCKER_FILE="docker/manylinux.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm/v7" >> $GITHUB_ENV

      - name: Cache Base Image
        uses: actions/cache@v3
        id: base-manylinux
        with:
          path: /tmp/.cache-base
          key: ${{ matrix.build_arch }}-base-${{ hashFiles( env.BASE_DOCKER_FILE ) }}

      - name: Create Cache Dir
        if: steps.base-manylinux.outputs.cache-hit != 'true'
        run: mkdir /tmp/.cache-base

      - name: Build Base Image
        if: steps.base-manylinux.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ env.BUILD_PLATFORM }}
          push: false
          tags: base-manylinux-${{ matrix.build_arch }}:latest
          file: ${{ env.BASE_DOCKER_FILE }}
          outputs: type=docker,dest=/tmp/.cache-base/base-manylinux-${{ matrix.build_arch }}.tar

      - name: Debug Step
        run: ls -la /tmp/.cache-base/

  musllinux:
    name: MuslLinux • ${{ matrix.build_arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_arch: [ "arm64", "amd64", "armv7" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ARM64 prepare
        if: matrix.build_arch == 'arm64'
        run: |
          echo BASE_DOCKER_FILE="docker/musllinux.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm64" >> $GITHUB_ENV

      - name: AMD64 prepare
        if: matrix.build_arch == 'amd64'
        run: |
          echo BASE_DOCKER_FILE="docker/musllinux.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/amd64" >> $GITHUB_ENV

      - name: ARMv7 prepare
        if: matrix.build_arch == 'armv7'
        run: |
          echo BASE_DOCKER_FILE="docker/musllinux.Dockerfile" >> $GITHUB_ENV
          echo BUILD_PLATFORM="linux/arm/v7" >> $GITHUB_ENV

      - name: Cache Base Image
        uses: actions/cache@v3
        id: base-musllinux
        with:
          path: /tmp/.cache-base
          key: ${{ matrix.build_arch }}-base-${{ hashFiles( env.BASE_DOCKER_FILE ) }}

      - name: Create Cache Dir
        if: steps.base-musllinux.outputs.cache-hit != 'true'
        run: mkdir /tmp/.cache-base

      - name: Build Base Image
        if: steps.base-musllinux.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ env.BUILD_PLATFORM }}
          push: false
          tags: base-musllinux-${{ matrix.build_arch }}:latest
          file: ${{ env.BASE_DOCKER_FILE }}
          outputs: type=docker,dest=/tmp/.cache-base/base-musllinux-${{ matrix.build_arch }}.tar

      - name: Debug Step
        run: ls -la /tmp/.cache-base/
